version: "3.8"

services:
  gracechurch-bot:
    build: .
    container_name: gracechurch-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PYTHONUNBUFFERED=1
